# Generated by Django 2.2.6 on 2019-10-31 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0004_auto_20191031_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='havetoread',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shelf.Category'),
        ),
    ]
