# Generated by Django 2.2.6 on 2019-11-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0005_auto_20191031_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='havetoread',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shelf.Category'),
        ),
        migrations.DeleteModel(
            name='author',
        ),
    ]
