# Generated by Django 2.2.6 on 2019-11-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0006_auto_20191110_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HaveToRead',
            new_name='NeedToRead',
        ),
        migrations.AlterField(
            model_name='needtoread',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shelf.Category'),
        ),
    ]
