# Generated by Django 2.2.6 on 2019-11-13 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0007_auto_20191110_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needtoread',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shelf.Category'),
        ),
    ]
