# Generated by Django 2.2.1 on 2019-10-31 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0003_bookauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaveToRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pictur', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Done', 'Done')], max_length=6)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shelf.BookAuthor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shelf.Category')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shelf.Publisher')),
            ],
        ),
        migrations.DeleteModel(
            name='articale',
        ),
    ]
